models:
  llm_model: 'gpt-5-chat'
  max_tokens: 4096
data:
  persona_path: 'data/Persona_Hub_200000.jsonl'
  conv_output_dir: 'data/raw_data/'
  qa_output_dir: 'data/raw_data/'
  result_path: 'results/'
  irrelevant_context_path: 'data/irrelevant_contexts.json'
  data_types: 'email'
  context_length: 32000
  self_verify: True
  clean: False
  num_persona: 1
inference:
  verbose: False
  parallel: False
  rate_limit_per_min: 5